#!/usr/bin/with-contenv bash

# Copy config to new location so it can be mounted read-only
cp /config/rclone.conf /tmp/rclone.conf
chown abc:abc /tmp/rclone.conf

while read -r l; do
  echo "Processing line: $l"

  # Parse line into array
  splitted=$(printf "%s" "$l" | xargs -n 1 printf "%s\n")
  readarray -t <<< "${splitted}"

  remote_name=${MAPFILE[0]}
  mount_point=/mnt/${MAPFILE[1]}
  params=("${MAPFILE[@]:2}")

  service_name=$(echo "$remote_name" | base64)
  mkdir -p "/etc/services.d/$service_name/"
  export mount_point remote_name params
  envsubst < /etc/defaults/run.sh > "/etc/services.d/$service_name/run"
  chmod +x "/etc/services.d/$service_name/run"
done </config/config.txt

echo "Done."
