#!/usr/bin/with-contenv bash

# Copy config to new location so it can be mounted read-only
cp /config/rclone.conf /tmp/rclone.conf
chown abc:abc /tmp/rclone.conf

while read -r l; do
  echo "Processing line: $l"
  eval "arr=($l)"
  remote_name=${arr[0]}
  mount_point=/mnt/${arr[1]}
  params=("${arr[@]:2}")
  service_name=$(echo "$remote_name" | base64)
  mkdir -p "/etc/services.d/$service_name/"
  export mount_point remote_name params
  envsubst < /etc/defaults/run.sh > "/etc/services.d/$service_name/run"
  chmod +x "/etc/services.d/$service_name/run"
done </config/config.txt

echo "Done."
